graph LR
  I{"Intellibrix"}
  I --> B["Brick"]
  I --> S("Structure")
  B --> S
  B --> P(("Program"))
  P --> St>"Step"]
  St --> A>"Action"]
  B --> D(("Database"))
  D --> M>"Memory"]
  D --> SQL>"SQL"]
  B --> AI(("Intelligence"))
  AI --> OAI>"OpenAI"]
  AI --> CAI>"Custom Function"]
  