graph LR
  I{"Intellibrix"}
  I --> B["Brick"]
  I --> S("Structure")
  B --> S
  P(("Program")) --> B
  St>"Step"] --> P
  A>"Action"]-->St
  D(("Database")) --> B
  M>"Memory"] --> D
  SQL>"SQL"] --> D
  AI(("Intelligence")) --> B
  OAI>"OpenAI"] --> AI
  CAI>"Custom Function"] --> AI
  